export const GET_TWEETS_REQUEST = "GET_TWEETS_REQUEST";
export const GET_TWEETS_RECEIVE = "GET_TWEETS_RECEIVE";
export const LOAD_TWEETS_REQUEST = "LOAD_TWEETS_REQUEST";
export const LOAD_TWEETS_RECEIVE = "LOAD_TWEETS_RECEIVE";
